export const songs = [
  { title: "Blinding Lights", artist: "The Weeknd", genre: "Pop" },
  { title: "Shape of You", artist: "Ed Sheeran", genre: "Pop" },
  { title: "Bohemian Rhapsody", artist: "Queen", genre: "Rock" },
  { title: "Billie Jean", artist: "Michael Jackson", genre: "Pop" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", genre: "Grunge" },
  { title: "Imagine", artist: "John Lennon", genre: "Soft Rock" },
  { title: "Hey Jude", artist: "The Beatles", genre: "Rock" },
  { title: "Rolling in the Deep", artist: "Adele", genre: "Soul" },
  { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", genre: "Funk" },
  { title: "Hotel California", artist: "Eagles", genre: "Rock" },
  {
    title: "Despacito",
    artist: "Luis Fonsi ft. Daddy Yankee",
    genre: "Reggaeton",
  },
  { title: "Old Town Road", artist: "Lil Nas X", genre: "Hip Hop" },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", genre: "Rock" },
  { title: "Shake It Off", artist: "Taylor Swift", genre: "Pop" },
  { title: "Hallelujah", artist: "Leonard Cohen", genre: "Folk" },
  { title: "All of Me", artist: "John Legend", genre: "R&B" },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", genre: "Pop" },
  { title: "Someone Like You", artist: "Adele", genre: "Pop" },
  { title: "Sweet Child o' Mine", artist: "Guns N' Roses", genre: "Rock" },
  { title: "Bad Guy", artist: "Billie Eilish", genre: "Alternative Pop" },
  { title: "Lose Yourself", artist: "Eminem", genre: "Hip Hop" },
  { title: "Thriller", artist: "Michael Jackson", genre: "Pop" },
  { title: "Let It Be", artist: "The Beatles", genre: "Rock" },
  {
    title: "Can't Stop the Feeling!",
    artist: "Justin Timberlake",
    genre: "Pop",
  },
  { title: "Levitating", artist: "Dua Lipa", genre: "Disco Pop" },
  { title: "Sunflower", artist: "Post Malone & Swae Lee", genre: "Hip Hop" },
  { title: "Drivers License", artist: "Olivia Rodrigo", genre: "Pop" },
  { title: "Boogie Wonderland", artist: "Earth, Wind & Fire", genre: "Disco" },
  {
    title: "I Will Always Love You",
    artist: "Whitney Houston",
    genre: "Ballad",
  },
  { title: "I Want It That Way", artist: "Backstreet Boys", genre: "Pop" },
  { title: "Born to Run", artist: "Bruce Springsteen", genre: "Rock" },
  { title: "Firework", artist: "Katy Perry", genre: "Pop" },
  { title: "Yesterday", artist: "The Beatles", genre: "Soft Rock" },
  { title: "Wonderwall", artist: "Oasis", genre: "Britpop" },
  { title: "Happy", artist: "Pharrell Williams", genre: "Pop" },
  { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", genre: "Pop" },
  { title: "Stayin' Alive", artist: "Bee Gees", genre: "Disco" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", genre: "Rock" },
  { title: "Toxic", artist: "Britney Spears", genre: "Pop" },
  { title: "Call Me Maybe", artist: "Carly Rae Jepsen", genre: "Pop" },
  { title: "Take On Me", artist: "A-ha", genre: "Synth-pop" },
  { title: "Africa", artist: "Toto", genre: "Rock" },
  {
    title: "Girls Just Want to Have Fun",
    artist: "Cyndi Lauper",
    genre: "Pop",
  },
  { title: "Stay", artist: "The Kid LAROI & Justin Bieber", genre: "Pop" },
  { title: "As It Was", artist: "Harry Styles", genre: "Pop" },
  { title: "Blowin' in the Wind", artist: "Bob Dylan", genre: "Folk" },
  { title: "Poker Face", artist: "Lady Gaga", genre: "Electropop" },
  { title: "Counting Stars", artist: "OneRepublic", genre: "Pop Rock" },
  { title: "7 Rings", artist: "Ariana Grande", genre: "R&B Pop" },
  {
    title: "Radioactive",
    artist: "Imagine Dragons",
    genre: "Alternative Rock",
  },
  { title: "No Woman, No Cry", artist: "Bob Marley", genre: "Reggae" },
  { title: "Gangnam Style", artist: "PSY", genre: "K-pop" },
  { title: "Hello", artist: "Adele", genre: "Pop" },
  { title: "Viva La Vida", artist: "Coldplay", genre: "Alternative Rock" },
  { title: "The Scientist", artist: "Coldplay", genre: "Alternative Rock" },
  { title: "Enter Sandman", artist: "Metallica", genre: "Metal" },
  {
    title: "Hips Don’t Lie",
    artist: "Shakira ft. Wyclef Jean",
    genre: "Latin Pop",
  },
  { title: "Tusa", artist: "KAROL G & Nicki Minaj", genre: "Reggaeton" },
  {
    title: "On The Floor",
    artist: "Jennifer Lopez ft. Pitbull",
    genre: "Dance",
  },
  { title: "In Da Club", artist: "50 Cent", genre: "Hip Hop" },
  { title: "Numb", artist: "Linkin Park", genre: "Nu Metal" },
  { title: "In The End", artist: "Linkin Park", genre: "Nu Metal" },
  { title: "Boulevard of Broken Dreams", artist: "Green Day", genre: "Rock" },
  { title: "Basket Case", artist: "Green Day", genre: "Punk Rock" },
  { title: "La Vida Es Un Carnaval", artist: "Celia Cruz", genre: "Salsa" },
  { title: "Don’t Stop Believin'", artist: "Journey", genre: "Rock" },
  {
    title: "We Found Love",
    artist: "Rihanna ft. Calvin Harris",
    genre: "Dance Pop",
  },
  { title: "Diamonds", artist: "Rihanna", genre: "Pop" },
  { title: "Stay With Me", artist: "Sam Smith", genre: "Pop" },
  { title: "Radio", artist: "Lana Del Rey", genre: "Dream Pop" },
  { title: "Bad Romance", artist: "Lady Gaga", genre: "Electropop" },
  { title: "Genie in a Bottle", artist: "Christina Aguilera", genre: "Pop" },
  { title: "Stronger", artist: "Kanye West", genre: "Hip Hop" },
  { title: "Jesus Walks", artist: "Kanye West", genre: "Hip Hop" },
  {
    title: "Empire State of Mind",
    artist: "Jay-Z & Alicia Keys",
    genre: "Hip Hop",
  },
  { title: "Bodak Yellow", artist: "Cardi B", genre: "Rap" },
  { title: "Peaches", artist: "Justin Bieber", genre: "R&B" },
  { title: "Monster", artist: "Shawn Mendes & Justin Bieber", genre: "Pop" },
  { title: "7 Years", artist: "Lukas Graham", genre: "Pop Soul" },
  { title: "Dance Monkey", artist: "Tones and I", genre: "Alternative Pop" },
  {
    title: "Somebody That I Used to Know",
    artist: "Gotye ft. Kimbra",
    genre: "Indie Pop",
  },
  { title: "Royals", artist: "Lorde", genre: "Electropop" },
  { title: "Counting Stars", artist: "OneRepublic", genre: "Pop Rock" },
  { title: "Demons", artist: "Imagine Dragons", genre: "Alternative Rock" },
  { title: "Finesse", artist: "Bruno Mars ft. Cardi B", genre: "Funk" },
  { title: "Treasure", artist: "Bruno Mars", genre: "Funk Pop" },
  { title: "Rock Your Body", artist: "Justin Timberlake", genre: "R&B" },
  { title: "SexyBack", artist: "Justin Timberlake", genre: "Electro-R&B" },
  { title: "No Tears Left to Cry", artist: "Ariana Grande", genre: "Pop" },
  { title: "Love Story", artist: "Taylor Swift", genre: "Country Pop" },
  { title: "You Belong with Me", artist: "Taylor Swift", genre: "Country Pop" },
  { title: "Blank Space", artist: "Taylor Swift", genre: "Pop" },
  { title: "Savage Love", artist: "Jawsh 685 & Jason Derulo", genre: "Pop" },
  { title: "Lollipop", artist: "Lil Wayne", genre: "Hip Hop" },
  { title: "Sicko Mode", artist: "Travis Scott", genre: "Trap" },
  { title: "Goosebumps", artist: "Travis Scott", genre: "Hip Hop" },
  { title: "Rockstar", artist: "DaBaby ft. Roddy Ricch", genre: "Rap" },
  { title: "Lucid Dreams", artist: "Juice WRLD", genre: "Hip Hop" },
  { title: "God’s Plan", artist: "Drake", genre: "Hip Hop" },
];
